version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.13
  volumes:
    - .:/lm:cached
    - ./node_modules:/lm/node_modules:delegated
    - yarn-cache:/.yarn-cache
  working_dir: /lm
  entrypoint: ["/lm/node_modules/.bin/micro-dev"]
  command: ["--port", "80"]
  environment:
    YARN_CACHE_FOLDER: /.yarn-cache
    NODE_ENV: development
    MONGO_URI: ${MONGO_URI-mongodb://mongodb:27017}
    URL_MONGO_URI: ${URL_MONGO_URI}
    MC_CLIENT_ID: ${MC_CLIENT_ID}
    MC_CLIENT_SECRET: ${MC_CLIENT_SECRET}



services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "6901:27017"

  mc-subscriber:
    <<: *node
    working_dir: /lm/services/mc-subscriber
    ports:
      - "6902:80"

  mc-click-event:
    << : *node
    working_dir: /lm/services/mc-click-event
    ports:
      - "6903:80"

  mc-send:
    <<: *node
    working_dir: /lm/services/mc-send
    ports:
      - "6904:80"

  identity:
    << : *node
    working_dir: /lm/services/identity
    depends_on:
      - mongodb
      - mc-subscriber
    ports:
      - "6905:80"

  mc-email:
    << : *node
    working_dir: /lm/services/mc-email
    ports:
      - "6906:80"

  mc-data-folder:
    << : *node
    working_dir: /lm/services/mc-data-folder
    ports:
      - "6907:80"

  email-category:
    << : *node
    working_dir: /lm/services/email-category
    ports:
      - "6908:80"

  email-deployment:
    << : *node
    working_dir: /lm/services/email-deployment
    depends_on:
      - mongodb
      - mc-email
      - email-category
    ports:
      - "6909:80"

  email-send:
    << : *node
    working_dir: /lm/services/email-send
    depends_on:
      - mongodb
      - mc-send
      - url
      - email-deployment
    ports:
      - "6910:80"

  mc-link-send:
    << : *node
    working_dir: /lm/services/mc-link-send
    ports:
      - "6911:80"

  url:
    << : *node
    working_dir: /lm/services/url
    ports:
      - "6912:80"

  event-poll:
    << : *node
    working_dir: /lm/services/event-poll
    entrypoint: ["node"]
    command: ["src/index.js"]
    depends_on:
      - mongodb

  identity-poll:
    << : *node
    working_dir: /lm/services/identity-poll
    entrypoint: ["node"]
    command: ["src/index.js"]
    depends_on:
      - identity

volumes:
  mongodb: {}
  yarn-cache: {}
