version: '3.7'

x-env-defaults: &env
  MC_GRAPHQL_URI: ${MC_GRAPHQL_URI-http://host.docker.internal:17430}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  URL_SERVICE_URL: ${URL_SERVICE_URL-http://url}
  QUEUE_SERVICE_URL: ${QUEUE_SERVICE_URL-http://queue}

x-node-defaults: &node
  tty: true
  init: true
  image: node:12.15
  working_dir: /lead-management
  restart: always
  volumes:
    - .:/lead-management:cached
    - ./node_modules:/lead-management/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  url:
    <<: *node
    working_dir: /lead-management/services/url
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    environment:
      <<: *env
    ports:
      - "16701:80"

  queue:
    <<: *node
    working_dir: /lead-management/services/queue
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    environment:
      <<: *env
    ports:
      - "16702:80"

volumes:
  yarn-cache: {}
