version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-service-urls: &env-service-urls
  URL_SERVICE_URL: ${URL_SERVICE_URL-http://url}
  QUEUE_SERVICE_URL: ${QUEUE_SERVICE_URL-http://queue}

x-env-mongodb: &env-mongodb
  MONGO_URI: ${MONGO_URI-mongodb://mongodb:27017}

x-env-mc-graphql: &env-mc-graphql
  MC_GRAPHQL_URI: ${MC_GRAPHQL_URI-http://host.docker.internal:17430}

x-env-brightcove: &env-brightcove
  BRIGHTCOVE_ACCOUNT_ID: ${BRIGHTCOVE_ACCOUNT_ID}
  BRIGHTCOVE_APP_ID: ${BRIGHTCOVE_APP_ID}
  BRIGHTCOVE_SECRET: ${BRIGHTCOVE_SECRET}

x-node-defaults: &node
  tty: true
  init: true
  image: node:12.15-alpine
  working_dir: /lead-management
  restart: always
  volumes:
    - .:/lead-management:cached
    - ./node_modules:/lead-management/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "${SERVER_DB_PORT-16700}:27017"

  click-log-forever:
    <<: *node
    working_dir: /lead-management/services/click-log
    entrypoint: ["../../node_modules/.bin/forever", "src/index.js"]
    environment:
      <<: *env
      <<: *env-service-urls
      <<: *env-mongodb
      <<: *env-mc-graphql
    depends_on:
      - mongodb
      - queue

  click-log:
    <<: *node
    working_dir: /lead-management/services/click-log
    entrypoint: ["node", "src/index.js"]
    environment:
      <<: *env
      <<: *env-service-urls
      <<: *env-mongodb
      <<: *env-mc-graphql
    depends_on:
      - mongodb
      - queue

  url:
    <<: *node
    working_dir: /lead-management/services/url
    entrypoint: ["../../node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 16701
    ports:
      - "16701:80"

  queue:
    <<: *node
    working_dir: /lead-management/services/queue
    entrypoint: ["../../node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongodb
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 16702
    depends_on:
      - mongodb
    ports:
      - "16702:80"

  identity:
    <<: *node
    working_dir: /lead-management/services/identity
    entrypoint: ["../../node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-service-urls
      <<: *env-mongodb
      <<: *env-mc-graphql
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 16703
    depends_on:
      - mongodb
      - queue
    ports:
      - "16703:80"

  identity-upsert:
    <<: *node
    working_dir: /lead-management/services/identity
    entrypoint: ["node", "src/tasks/upsert-from-queue"]
    environment:
      <<: *env
      <<: *env-service-urls
      <<: *env-mongodb
      <<: *env-mc-graphql
    depends_on:
      - mongodb
      - queue

  identity-upsert-forever:
    <<: *node
    working_dir: /lead-management/services/identity
    entrypoint: ["../../node_modules/.bin/forever", "src/tasks/upsert-from-queue"]
    environment:
      <<: *env
      <<: *env-service-urls
      <<: *env-mongodb
      <<: *env-mc-graphql
    depends_on:
      - mongodb
      - queue

  video:
    <<: *node
    working_dir: /lead-management/services/video
    entrypoint: ["node", "src/tasks/sync"]
    environment:
      <<: *env
      <<: *env-mongodb
      <<: *env-brightcove
    depends_on:
      - mongodb

volumes:
  mongodb: {}
  yarn-cache: {}
